### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by volodymyrzdrok** [volodymyrzdrok/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by vozdrok** [comment]
<p>He is  an employer from an American family, born in South Africa, created a company "space relations", called it "<a href="https://www.spacex.com/" target="_blank">Space-X</a>". I make rockets and spaceships. Chief Executive Officer of the electric car manufacturer <a href="https://www.tesla.com"  target="_blank">Tesla</a>-love.</p>
