### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by volodymyrzdrok** [volodymyrzdrok/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by vozdrok** [comment]
s earliest venture was the founding of Zip2, a company that provided maps and business directories to newspapers and was later sold in 1999 to Compaq for $307 million.

1999
Paypal, erstwhile X.com, was what eventually made Musk his fortune. Founded in 1999, Paypal was then acquired by Ebay for $1.5 billion, of which $165 million was given to Musk in stocks.

2002

Musk founded Space Exploration Technologies, better known as SpaceX. Musk was convinced that humanity's survival depended on its ability to become a multi-planetary species, but current rocket launching technologies were too expensive. This he accomplished with the launch of the Falcon 1 in 2006, the Falcon 9 in 2010 and the Falcon Heavy in 2018.
